# Generated by Django 3.0.7 on 2020-06-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdsysClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstituteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutename', models.CharField(max_length=50)),
                ('targetline', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('logo', models.FileField(default='student_icon.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('sub_category', models.CharField(max_length=30)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.EdsysClass')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
