# Generated by Django 3.0.7 on 2020-06-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200613_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=30)),
                ('registration_num', models.IntegerField()),
                ('Admission_date', models.DateField()),
                ('photo', models.FileField(default='student_icon.png', upload_to='images')),
                ('mobile_num', models.IntegerField(unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('caste', models.CharField(max_length=30)),
                ('previous_school', models.CharField(max_length=50)),
                ('orphan_student', models.BooleanField(blank=True)),
                ('religion', models.CharField(choices=[('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('islam', 'Islam'), ('jainism', 'Jainism'), ('sikhism', 'Sikhism'), ('other', 'Other')], default='hinduism', max_length=20)),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=20)),
                ('father_education', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('father_income', models.FloatField(blank=True, null=True)),
                ('father_mobile', models.IntegerField()),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_education', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_income', models.FloatField(blank=True, null=True)),
                ('mother_mobile', models.IntegerField(blank=True, null=True)),
                ('name_of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.EdsysClass')),
            ],
        ),
    ]
