# Generated by Django 3.0.7 on 2020-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteinfo',
            name='logo',
            field=models.FileField(default='student_icon.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(default='student_icon.png', upload_to='images/'),
        ),
    ]
