# Generated by Django 3.0.7 on 2020-06-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200613_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteinfo',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
