# Generated by Django 3.0.7 on 2020-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
