# Generated by Django 3.0.7 on 2020-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200623_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_photo',
            field=models.FileField(default='employee_icon.png', upload_to='images'),
        ),
    ]
