# Generated by Django 3.0.7 on 2020-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense_description', models.TextField()),
                ('expense_amount', models.IntegerField()),
            ],
        ),
    ]
