# Generated by Django 3.0.7 on 2020-07-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20200702_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
