# Generated by Django 3.0.7 on 2020-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20200703_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_amount', models.IntegerField()),
                ('income_description', models.TextField()),
            ],
        ),
    ]
