# Generated by Django 3.0.7 on 2020-07-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Class', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Attendance', models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('leave', 'leave')], max_length=20)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.EdsysClass')),
                ('StudentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Student')),
            ],
        ),
    ]
